create table if not exists public.content_records (
  id bigint generated by default as identity primary key,
  record_type text not null,
  record_key text not null,
  data jsonb not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (record_type, record_key)
);

create index if not exists content_records_type_position_idx
  on public.content_records (record_type, position);

create index if not exists content_records_data_gin_idx
  on public.content_records using gin (data);

alter table public.content_records enable row level security;

drop policy if exists "Service role can manage content records" on public.content_records;

create policy "Service role can manage content records"
  on public.content_records
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create table if not exists public.admin_events (
  id bigint generated by default as identity primary key,
  record_type text not null,
  operation text not null,
  record_key text,
  created_at timestamptz not null default now()
);

create index if not exists admin_events_created_at_idx
  on public.admin_events (created_at desc);

alter table public.admin_events enable row level security;

drop policy if exists "Anyone can read admin event pings" on public.admin_events;
drop policy if exists "Service role can manage admin event pings" on public.admin_events;

create policy "Anyone can read admin event pings"
  on public.admin_events
  for select
  using (true);

create policy "Service role can manage admin event pings"
  on public.admin_events
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

grant select on public.admin_events to anon, authenticated;

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'admin_events'
  ) then
    alter publication supabase_realtime add table public.admin_events;
  end if;
end $$;
