create table if not exists public.content_records (
  id bigint generated by default as identity primary key,
  record_type text not null,
  record_key text not null,
  data jsonb not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (record_type, record_key)
);

create index if not exists content_records_type_position_idx
  on public.content_records (record_type, position);

create index if not exists content_records_data_gin_idx
  on public.content_records using gin (data);

alter table public.content_records enable row level security;

drop policy if exists "Service role can manage content records" on public.content_records;

create policy "Service role can manage content records"
  on public.content_records
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
